#AWS S#
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: onstagram
    stack:
      auto: false
    credentials:
      secret-key:  #gitignore에 넣어서 깃에 업로드 안되게 하기
      access-key: