#H2
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/onstagram
#    username: onstagram
#    password: 123
#    driver-class-name: org.h2.Driver

#oracle
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: onstagram
    password: 123
    driver-class-name: oracle.jdbc.OracleDriver


  jpa:
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl.auto: update
        format_sql: true
    database: oracle
    database-platform: org.hibernate.dialect.OracleDialect

  servlet:
    multipart:
      enabled: true #파일 업로드 가능 여부
      location: C:\\image #업로드된 파일의 임시 저장 경로
      max-request-size: 100MB #한 번에 최대 업로드 가능한 용량
      max-file-size: 20MB #파일 하나의 최대 크기

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8888